# Generated by Django 5.1.15 on 2026-05-12 01:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('is_notifiable', models.BooleanField(default=True)),
                ('incubation_period_days', models.PositiveIntegerField(default=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('population', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_count', models.PositiveIntegerField(default=1)),
                ('onset_date', models.DateField()),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('suspected', 'Suspected'), ('confirmed', 'Confirmed'), ('negative', 'Negative'), ('recovered', 'Recovered'), ('deceased', 'Deceased')], default='suspected', max_length=15)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], default='mild', max_length=10)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('symptoms', models.TextField(blank=True)),
                ('lab_confirmed', models.BooleanField(default=False)),
                ('hospitalized', models.BooleanField(default=False)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='surveillance.disease')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='surveillance.district')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('case_count', models.PositiveIntegerField()),
                ('threshold', models.PositiveIntegerField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='surveillance.disease')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='surveillance.district')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='surveillance.province'),
        ),
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases_per_week', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='surveillance.disease')),
                ('district', models.ForeignKey(blank=True, help_text='Leave blank for nationwide threshold', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='surveillance.district')),
            ],
            options={
                'unique_together': {('disease', 'district')},
            },
        ),
    ]
